name: Metrics

on:
  # Schedule updates (once a day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Isocalendar Plugin (existing)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # Languages Activity Plugin
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          commits_authoring: kcodess2807, kcodess2807@users.noreply.github.com

      # Recently Starred Plugin
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.stars.svg
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 4

      # Coding Habits Plugin - Facts
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.habits.facts.svg
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_from: 200
          plugin_habits_days: 14
          config_timezone: Asia/Kolkata

      # Coding Habits Plugin - Charts
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.habits.charts.svg
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_trim: yes
          config_timezone: Asia/Kolkata

      # Follow-up Plugin - Issues & PRs
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.followup.svg
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_followup_archived: no

      # GitHub Skyline Plugin
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics.plugin.skyline.svg
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2024
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5

      # AniList Plugin
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics.plugin.anilist.svg
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 2
          plugin_anilist_user: .user.login
